keys:
  - &root_fovirbox age172xqa230e5vwzsdajc6ak235qvg448nf9g02xjp80w3vknsacd3qszzc87

creation_rules:
  - path_regex: machines/fovirbox/values/.*
    key_groups:
      - age:
          - *root_fovirbox
