{...}: {
  imports = [
    ./abolish.nix
    ./aerial.nix
    ./bufferline.nix
    ./cmp-conventionalcommits.nix
    ./colorizer.nix
    ./comment.nix
    ./conform-nvim.nix
    ./cybu.nix
    ./dashboard.nix
    ./direnv.nix
    ./emmet.nix
    ./gitsigns.nix
    ./guess-indent.nix
    ./hop.nix
    ./indent-blankline.nix
    ./leetcode.nix
    ./lsp
    ./lspsaga.nix
    ./lualine.nix
    ./luasnip.nix
    ./markdown.nix
    ./mini.nix
    ./neo-tree.nix
    ./neogen.nix
    ./noice.nix
    ./nvim-autopairs.nix
    ./nvim-cmp.nix
    ./nvim-surround.nix
    ./persistence.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./ts-autotag.nix
    ./vim-matchup.nix
    ./wakatime.nix
    ./web-devicons.nix
    ./which-key.nix
  ];
}
