{
  imports = [
    ../values/sci.nix
    ./caddy.nix
    ./ensure-path.nix
    ./fusion.nix
    ./gotify-fail2ban.nix
    ./gotify.nix
    ./openlist.nix
    ./polaris.nix
    ./postgres.nix
    ./radicale.nix
    ./redis.nix
    ./restic.nix
    ./rsshub.nix
    ./searxng.nix
    ./social.nix
    ./stump.nix
    ./syncthing.nix
    ./umami.nix
    ./wakapi.nix
  ];
}
