{
  imports = [
    ./caddy.nix
    ./ensure-path.nix
    ./fusion.nix
    ./openlist.nix
    ./overleaf.nix
    ./polaris.nix
    ./postgres.nix
    ./radicale.nix
    ./redis.nix
    ./restic.nix
    ./rsshub.nix
    ./sci.nix
    ./searxng.nix
    ./stump.nix
    ./syncthing.nix
    ./umami.nix
    ./wakapi.nix
  ];
}
